ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'MFA_ENROLLMENT_STARTED';
ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'MFA_ENABLED';
ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'MFA_CHALLENGE_SUCCESS';
ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'MFA_CHALLENGE_FAILURE';
ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'MFA_RECOVERY_CODE_USED';

ALTER TABLE "AdminUser"
  ADD COLUMN IF NOT EXISTS "ativo" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "sessionVersion" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "totpSecretEncrypted" TEXT,
  ADD COLUMN IF NOT EXISTS "totpPendingSecretEncrypted" TEXT,
  ADD COLUMN IF NOT EXISTS "totpPendingExpiresAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "totpEnabledAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "totpLastUsedStep" BIGINT,
  ADD COLUMN IF NOT EXISTS "recoveryCodeHashes" JSONB;
