DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AdminRole') THEN
    CREATE TYPE "AdminRole" AS ENUM ('MASTER', 'ADMIN');
  END IF;
END $$;

ALTER TABLE "AdminUser"
  ADD COLUMN IF NOT EXISTS "role" "AdminRole" NOT NULL DEFAULT 'ADMIN';

UPDATE "AdminUser"
SET "role" = 'MASTER'
WHERE LOWER(COALESCE("emailNormalizado", "email", '')) = 'joao.murat30@gmail.com';

DO $$
BEGIN
  ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'PASSWORD_CHALLENGE_SUCCESS';
  ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'PASSWORD_CHANGED';
  ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'INVITE_EMAIL_SENT';
  ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'INVITE_REVOKED';
  ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'USER_ACTIVATED';
END $$;
